"""
main.py  –  FastAPI server
--------------------------
Exposes a single POST /describe-image endpoint.
The client uploads an image file; the server returns a JSON description
generated by GPT-4o-mini via LangChain.

Run with:
    uvicorn main:app --reload --host 0.0.0.0 --port 8000
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from langchain_chain import describe_image   # our LangChain module

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Image Description API",
    description="Upload an image and receive a detailed description from GPT-4o-mini.",
    version="1.0.0",
)

# Allow all origins (adjust in production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Response schema
# ---------------------------------------------------------------------------

class DescriptionResponse(BaseModel):
    filename: str
    content_type: str
    description: str


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", summary="Health check")
async def root():
    """Simple health-check endpoint."""
    return {"status": "ok", "message": "Image Description API is running 🚀"}


@app.post(
    "/describe-image",
    response_model=DescriptionResponse,
    summary="Describe an uploaded image",
)
async def describe_image_endpoint(
    file: UploadFile = File(..., description="Image file to describe (JPEG, PNG, GIF, WEBP)"),
):
    """
    Accept an image file, send it to GPT-4o-mini via LangChain,
    and return the generated description.
    """
    # ── Validate MIME type ──────────────────────────────────────────────────
    allowed_types = {"image/jpeg", "image/png", "image/gif", "image/webp"}
    content_type = file.content_type or ""
    if content_type not in allowed_types:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported media type: {content_type}. "
                   f"Allowed types: {', '.join(sorted(allowed_types))}",
        )

    # ── Read image bytes ────────────────────────────────────────────────────
    image_bytes = await file.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    # ── Call LangChain chain ────────────────────────────────────────────────
    try:
        description = describe_image(image_bytes, media_type=content_type)
    except EnvironmentError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Error communicating with OpenAI: {e}",
        )

    return DescriptionResponse(
        filename=file.filename or "unknown",
        content_type=content_type,
        description=description,
    )


# ---------------------------------------------------------------------------
# Dev entry-point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("mai:app", host="0.0.0.0", port=9000, reload=True)
